name: GitHub Actions Demo
run-name: GitHub Actions Demo Run
on: 
# Webhook Events
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/workflows'
  issues:
    types: [opened, reopened]

   # Scheduled events
  schedule:
    # - cron: '*/15 * * * *'
    # - cron: '0 9-17 * * *'
    - cron: '11 11 * * 5'

  # Manual events
  workflow_dispatch:  
    
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Print greeting
        run: echo Hello, world!
      

      - name: Writing to Workflow log
        run: |
          echo "Writing to Workflow Log"
          echo "::group::Writing to the log"
          echo "::notice file=starter.yml,line=169,col=19,endColumn=22::Writing a notice"
          echo "::Warning file=starter.yml,line=171,col=19,endColumn=22::Writing a Warning"
          echo "::endgroup::"
      
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"


